import Plutchik from "@psychological-components/plutchik";
import "@psychological-components/plutchik/lib/theme-core.css";

Plutchik.default({
  element: "#drawer",
  maxElements: 32,
  checkedElements: [
    "ecstasy",
    "admiration",
    "terror",
    "amazement",
    "grief",
    "loathing",
    "rage",
    "vigilance",
    "joy",
    "trust",
    "fear",
    "surprise",
    "sadness",
    "disgust",
    "anger",
    "anticipation",
    "serenity",
    "acceptance",
    "apprehension",
    "distraction",
    "pensiveness",
    "boredom",
    "annoyance",
    "interest",
    "optimistm",
    "love",
    "submission",
    "awe",
    "disapproval",
    "emorse",
    "contempt",
    "aggressiveness",
  ],
  labels: [
    [
      "ecstasy",
      "admiration",
      "terror",
      "amazement",
      "grief",
      "loathing",
      "rage",
      "vigilance",
    ],
    [
      "joy",
      "trust",
      "fear",
      "surprise",
      "sadness",
      "disgust",
      "anger",
      "anticipation",
    ],
    [
      "serenity",
      "acceptance",
      "apprehension",
      "distraction",
      "pensiveness",
      "boredom",
      "annoyance",
      "interest",
    ],
    [
      "optimistm",
      "love",
      "submission",
      "awe",
      "disapproval",
      "emorse",
      "contempt",
      "aggressiveness",
    ],
  ],
  isMobile: false,
  lang: "en",
});